export default en = {
    descriptionHome: "View your favorite Pokémon's data",
    buttonHome: "Go on",
    loading: "Loading",
    pokemonLoading: "Loading pokémon",
    label: "No elements selected",
    grass: 'Grass',
    poison: 'Poison',
    fire: 'Fire',
    flying: 'Flying',
    water: 'Water',
    bug: 'Bug',
    normal: 'Normal',
    electric: 'Electric',
    ground: 'Ground',
    fairy: 'Fairy',
    fighting: 'Fighting',
    psychic: 'Psychic',
    rock: 'Rock',
    ice: 'Ice',
    dragon: 'Dragon',
    steel: 'Steel',
    dark: 'Dark',
    types: 'Types',
    xp: 'Basic experience when defeating',
    height: "Pokémon's height",
    meter: 'meter',
    weight: "Pokémon's weight",
    kilos: 'kilos',
    abilities: 'Abilities',
    amount: 'amount of initial ',
    inicial: '',
    version: 'version',
    default: 'default',
    moves: 'Moves',
    learn: 'Can learn at the level',
    like: 'Did you like the app?',
    opnion: 'Rate our app so we know your opinion',
    notNow: 'Not now',
    rate: 'Rate the app'
}