export default pt = {
    descriptionHome: 'Veja os dados de seus pokémons favoritos',
    buttonHome: 'Seguir',
    loading: 'Carregando',
    pokemonLoading: 'Carregando mais pokémons',
    label: 'Nenhum elemento selecionado',
    grass: 'Grama',
    poison: 'Veneno',
    fire: 'Fogo',
    flying: 'Voador',
    water: 'Água',
    bug: 'Inseto',
    normal: 'Normal',
    electric: 'Eletrico',
    ground: 'Terra',
    fairy: 'Fada',
    psychic: 'Psiquico',
    rock: 'Pedra',
    ice: 'Gelo',
    dragon: 'Dragão',
    steel: 'Metal',
    dark: 'Sombrio',
    types: 'Elementos',
    xp: 'Experiência básica ao derrotar',
    height: 'Altura do pokémon',
    meter: 'metros',
    weight: 'Peso do pokémon',
    kilos: 'quilos',
    abilities: 'Habilidades',
    amount: 'quantidade de ',
    inicial: 'inicial',
    version: 'versões',
    default: 'padrão',
    moves: 'Lista de movimentos',
    learn: 'Pode aprender no nivel',
    like: 'Gostou do aplicativo?',
    opnion: 'Deixe uma avaliação para sabermos sua opnião',
    notNow: 'Agora não',
    rate: 'Avaliar'
}