export default pt = {
    descriptionHome: 'Veja os dados de seus pokémons favoritos',
    buttonHome: 'Seguir',
    loading: 'Carregando',
    pokemonLoading: 'Carregando mais pokémons',
    label: 'Nenhum elemento selecionado',
    grass: 'Grama',
    poison: 'Veneno',
    fire: 'Fogo',
    flying: 'Voador',
    water: 'Água',
    bug: 'Inseto',
    normal: 'Normal',
    electric: 'Eletrico',
    ground: 'Terra',
    fairy: 'Fada',
    psychic: 'Psiquico',
    rock: 'Pedra',
    ice: 'Gelo',
    dragon: 'Dragão',
    steel: 'Metal',
    dark: 'Sombrio'
}